.circleci/config.yml
package.json

Enforce Node.js `8.x` requirement through `engines.node` in the root `package.json`. Also updates CircleCI image.
**New**
**Changed**
- `.circleci/config.yml` now uses `circleci/node:8`
- `package.json` now species `8.x` for `engines.node`
**Removed**

chore(project): update engines.node and circle CI to Node.js 8.x

---

docs/dependencies.md

Closes #
Little fix to make language more direct.
For some reason the diff is not very helpful here, but basically the change involves one sentence, as explained below...
**Changed**
- Changes `this document looks to show how we're looking to address` to `we are addressing`

docs: update language in dependencies doc to be more direct

---

.github/CONTRIBUTING.md

There are Contribution Guidelines linked on the main README.md (https://github.com/ibm/carbon-elements#-contributing), but unfortunately it 404s.
I added a `CONTRIBUTING.md` file based on the `carbon-components-react` contributing guidelines (https://github.com/IBM/carbon-components-react/blob/master/.github/CONTRIBUTING.md), but I modified them slightly to better suit this repo.
**New**
- Add `.github/CONTRIBUTING.md`

docs: add basic contributing doc following carbon-components-react template

---

packages/icon-helpers/src/index.js

Refs IBM/carbon-components#1452.
**New**
- Named export for [`formatAttributes()`](
https://github.com/IBM/carbon-elements/blob/v0.0.1-alpha.12/packages/icon-helpers/src/toString.js#L17-L25) function.

feat(icon-helpers): export formatAttributes

---

packages/icons-angular/package.json

This way consumers don't need to add it as a dependency! (oops 😅)

fix(icons-angular): add icon-helpers as a direct dependency

---

packages/icons-vue/README.md

Closes #115
Adds an alternative example of how icons can be imported into individual components instead of being registered globally. This might be useful if an icon is only being used in a single component and in cases where components are being lazy-loaded into the application.
**New**
- Example in README showcasing another way Carbon icons can be used in a Vue project

docs(readme): add alt example for importing icons not globally

---

packages/layout/scss/_key-height.scss

Closes #118
**New**
**Changed**
- `@carbon/layout`
- Remove `map-deep-get` usage
- Verify breakpoints has default value
**Removed**

fix(layout): remove map-deep-get usage

---

packages/icon-helpers/src/toSVG.js

Closes #110 
**New**
**Changed**
- `@carbon/icon-helpers`
- Fix usage of `getAttributes`
**Removed**

fix(icon-helpers): use attributes correctly in toSVG

---

packages/icon-helpers/src/getAttributes.js
packages/icon-helpers/src/index.js
packages/icons-react/src/createFromInfo.js
packages/icons/examples/esm/index.js

Came up today during icon review. 16x16 icons are blurry in Firefox Quantum, we need the custom `style` attribute added for each icon to prevent this.
**New**
**Changed**
- `style` default attribute added to `@carbon/icon-helpers`
- Update implementations that need style objects, namely `@carbon/icons-react`
**Removed**

Fix icon blurriness issue in Firefox Quantum

---

packages/colors/src/build.js

**Changed**
- use `PREFIX` variable for colors map name
- follow naming convention and use `colors` instead of singular `color`

fix(colors): update scss map name

---

packages/type/scss/_styles.scss
packages/type/src/__tests__/__snapshots__/styles-test.js.snap
packages/type/src/styles.js

expressive-heading-04 values at sm, med, and large breakpoints were updated in order to prevent our H1 and H2s from becoming that same size at mobile and tablet.

Value update for expressive-heading-04 token

---

packages/type/src/styles.js

There were conflicting weights on the IDL site; the brand team likes to use the light (300) weight on black backgrounds and regular (400) weight on light backgrounds for fonts of the same size. 
We have to pick a lane and stick with the Regular (400) weight for $expressive-heading-04 (all steps) $expressive-heading-05 (step 7) and $productive-heading-04. 
Basically reverting back to what we had before... apologize for the confusion!!!

Revert to previous weights on several heading tokens

---

packages/icons-react/src/__tests__/createFromInfo-test.js
packages/icons-react/src/createFromInfo.js

Closes #228 
This PR uses `React.forwardRef` to preserve React refs on the rendered SVG
**Changed**
- wrap icon modules with `React.forwardRef`

feat(icons-react): attach refs to rendered SVG icon components

---

packages/icons-handlebars/index.js

Update export pattern for `icons-handlebars` to correctly export `iconHelper`
**New**
**Changed**
- `@carbon/icons-handlebars`
- Update export pattern
**Removed**

fix(icon-handlebars): update exports pattern

---

packages/icons-handlebars/index.js

Closes #256 
**Changed**
- iconHelper tests parameter to determine if `hash` property exists to use the conventional handlebars input or it's a custom object and the full object should be used to apply attributes to an icon.

Adds the ability to pass an object to carbon-icon handlebars helper

---

packages/colors/__tests__/__snapshots__/colors-test.js.snap
packages/colors/__tests__/colors-test.js
packages/themes/src/__tests__/themes-test.js
packages/themes/src/g10.js
packages/themes/src/g100.js
packages/themes/src/g90.js
packages/themes/src/white.js
packages/type/src/__tests__/__snapshots__/styles-test.js.snap
tasks/ci-check.js

Closes #262 
**New**
**Changed**
- Add `active-01` and `hover-field` as deprecated tokens in `@carbon/themes`
**Removed**

fix(themes): add in deprecated tokens

---

packages/type/scss/_styles.scss
packages/type/src/__tests__/__snapshots__/styles-test.js.snap
packages/type/src/styles.js

Updating the expressive paragraph token to be light weight at all breakpoints. Meets the requirements for / design and mimics the use of this type style on the IDL site.
Light on the left (on IDL) looks much more pronounced with semi-bold than regular.

Make $expressive-paragraph-01 Light (not Reg)

---

packages/type/scss/_reset.scss
packages/type/src/reset.js

Closes #276
**New**
**Changed**
- Update resets to use `font-weight: 600` for `strong` elements
**Removed**

fix(type): change font weight for strong

---

packages/icons-react/src/createFromInfo.js

Closes #303
This PR removes the `title` property from the `propTypes` object

refactor(icons-react): remove unneeded propType declaration

---

packages/themes/src/g10.js
packages/themes/src/g100.js
packages/themes/src/g90.js
packages/themes/src/white.js

I propose adding a `$highlight` token per this comment here: https://github.com/IBM/carbon-components/issues/1710#issuecomment-459804553
cc @IBM/carbon-designers 
Currently `Datepicker` highlight is set directly with a color variable instead of a token. Unfortunately this color variable won't work for g90 and g100 themes.
So as it stands, the only way to fix this issue with the current `@carbon/themes` setup is to add a new token. This `$highlight` token will allow `DatePicker` to be updated in such a way that makes it a11y compliant for g90 and g100 themes.
**New**
- add `$highlight` token
**Changed**
- set `$highlight` for each existing theme (blue20 for light themes, blue90 for dark ui themes like g90 and g100)

feat(themes): add highlight token

---

packages/motion/README.md
packages/motion/scss/motion.scss

Closes #https://github.com/IBM/carbon-elements/issues/325
Use `transition-timing-function` which accepts a `cubic-bezier` as opposed to `transition-property` which expects a CSS property.
**Changed**
- Use `transition-timing-function` instead of `transition-property`

fix(motion): use correct css property

---

packages/type/src/fluid.js

It doesn't take a radix like parseInt does 🤷‍♂️

fix: parseFloat only has one parameter

---

packages/icons-angular/config/tsconfig-aot.json
packages/icons-angular/src/build.js
packages/icons-angular/src/templates.js

closes #350 
Essentially just removes a whole bunch of dead code. since we were already building the `NgModule`s as part of the components, consumers just have to `import { SomeIconSizeModule } from "@carbon/icons-angular/lib/some-icon/size"` (Instead of importing the module directly from the index)

fix(icons-angular): remove massive default entrypoint

---

packages/themes/src/g100.js
packages/themes/src/g90.js

PR based on @shixiedesign's comment here: https://github.com/IBM/carbon-components/issues/1731#issuecomment-461562980
> Change token `$support-02` ’s values to Green 50 / `#24A148` on both light themes, and Green 40 / `#3DBB61` on both dark themes.
**Changed**
- change `$support-02` to green40 for g90 and g100 themes

fix(themes): update support02 for g90 and g100

---

packages/themes/src/g10.js
packages/themes/src/g100.js
packages/themes/src/g90.js
packages/themes/src/white.js

Closes https://github.com/IBM/carbon-elements/issues/366
Adding two additional tokens so Tabs and links get the accessible blues: `$interactive-04`, `$link-01`
Related: https://github.com/IBM/carbon-components/issues/1757

add interactive-04 and link-01

---

packages/icons/src/svgo.js

Support hidden paths (`opacity="0"`) and add option to preserve ids in `cleanupIDs` pass.
**New**
**Changed**
- `icons`
- Update SVGO plugins
**Removed**

feat(icons): support hidden paths and preserve ids

---

docs/migration/10.x-themes.md

Closes #401
Add initial migration guide for 10.x for `carbon-themes` -> `@carbon/themes`.
**New**
- Add initial migration guide for 10.x for `carbon-themes` -> `@carbon/themes`
**Changed**
**Removed**

docs(themes): add 10.x migration guide

---

docs/guides/verifying-icons.md
docs/migration/10.x-grid.md
docs/migration/10.x-layout.md
docs/publishing.md
docs/technical-preview.md

Closes #271 
Add migration guides for grid and layout.
**New**
- Add migration guides for grid and layout
**Changed**
**Removed**

 docs(migrate): add layout docs

---

package.json

**Changed**
- A change to run StyleLint only for staged files when it runs upon commit. In old code, it ran against all CSS/Sass files in the project.

chore(lint): running StyleLint only for staged files

---

packages/type/examples/preview/styles.scss
packages/type/scss/font-face/_sans.scss
packages/type/scss/font-face/_serif.scss

Closes #456
Plex Mono remains unchanged
**New**
- Support for Greek language subset in IBM Plex Sans
**Changed**
- IBM Plex Sans `v4`→`v6`
- IBM Plex Serif `v5`→`v7`

chore: update fonts to latest version and add greek support for sans

---

packages/type/examples/preview/index.js
packages/type/examples/preview/styles.scss
packages/type/scss/_reset.scss
packages/type/scss/_styles.scss
packages/type/src/__tests__/__snapshots__/styles-test.js.snap
packages/type/src/__tests__/fluid-test.js
packages/type/src/reset.js
packages/type/src/styles.js

Part of #393, we need to support alternative `font-family` definitions for our type styles. The update to the preview example is to show that these styles should work in other languages.
**New**
**Changed**
- Type styles no longer include `font-family` in their definition
- The type reset now has optional body/mono/base-font-size arguments
**Removed**

fix(type): allow type styles to inherit font-family

---

docs/migration/10.x-color.md

Closes #466
Fix typo in migration guide
**New**
**Changed**
- `docs/migration/10.x-color.md` now uses `interactive` token naming
**Removed**

docs(migration): update to correct token name

---

packages/type/scss/font-face/_mono.scss
packages/type/scss/font-face/_sans.scss
packages/type/scss/font-face/_serif.scss
packages/type/scss/font-face/_settings.scss

Closes #476
The default setting here doesn't change any behavior. User's can optionally override the `$carbon--font-display` variable to suit their application's Flash of Unstyled Text (FOUT) tolerance.
Additional, future, settings could include: 
- additional weights
- exclude `local()` src
- special characters
**New**
- `font-face/_settings.scss`
- `font-display` in font face declarations

feat: add font-display setting to enhance font loading experience

---

packages/icons/package.json

Update `@carbon/icons` to include `scss` folder in `files`.

fix(icons): include scss folder in package

---

packages/icons-angular/README.md
packages/icons-react/README.md
packages/icons-vue/README.md

Closes #482 
Update icon library READMEs to reflect current guidance for finding import path.
**New**
**Changed**
- `icons-*` packages now use correct import paths and reference netlify demo for looking up path
**Removed**

docs(icons-*): update icon READMEs

---

packages/bundler/src/bundler.js
packages/bundler/src/commands/sassdoc.js
packages/colors/package.json
packages/elements/docs/sass.md
packages/elements/package.json
packages/grid/package.json
packages/icons/package.json
packages/import-once/package.json
packages/layout/package.json
packages/motion/package.json
packages/themes/package.json
packages/type/docs/sass.md
packages/type/package.json

- was previously just a directory entry point
Closes #495 
Example, if grid build looks like
`bundler sassdoc 'scss/*.scss'`
And there are now `_inlined` and `vendor` SCSS directories to ignore for SassDoc purposes, use
`bundler sassdoc 'scss/*.scss' -i 'scss/{_inlined,vendor}'`
And the elements package will probably want to do something like
`bundler sassdoc 'scss/**/*.scss' -i 'scss/**/{_inlined,vendor}'`
Because the `scss` directory isn't flat.

fix(sassdoc): allow source glob support

---

docs/migration/10.x-color.md

The migration docs show a new variable `interaction-04`, but it's actually called `interactive-04`. This fixes the typo
**Changed**
- Replaced incorrect variable name `interaction-04` with `interactive-04` in 10.x-color.md

chore(docs): fix typo in color variable migration docs

---

packages/icons-react/src/__tests__/createFromInfo-test.js
packages/icons-react/src/createFromInfo.js

Closes #498
**New**
**Changed**
- Update `createFromInfo` to not camel-case `data-` attributes
**Removed**

fix(icons-react): data attributes are no longer transformed
