IBM/carbon-elements

packages/type/examples/basic/index.html
packages/type/examples/basic/styles.scss
packages/type/scss/_spacing.scss
packages/type/scss/_styles.scss
packages/type/scss/type.scss

Closes #40 
Update type values with new proposal, add in additional tokens.
**New**
**Changed**
- `@carbon/type`
- New type styles added
- Updated demo to show additional font styles
**Removed**

feat(type): update type values and add additional tokens

---

packages/icons/src/svg/16/caret--down.svg
packages/icons/src/svg/16/caret--left.svg
packages/icons/src/svg/16/caret--right.svg
packages/icons/src/svg/16/caret--sort--down.svg
packages/icons/src/svg/16/caret--sort--up.svg
packages/icons/src/svg/16/caret--sort.svg
packages/icons/src/svg/16/caret--up.svg
packages/icons/src/svg/16/chevron--down.svg
packages/icons/src/svg/16/chevron--left.svg
packages/icons/src/svg/16/chevron--right.svg
packages/icons/src/svg/16/chevron--sort--down.svg
packages/icons/src/svg/16/chevron--sort--up.svg
packages/icons/src/svg/16/chevron--sort.svg
packages/icons/src/svg/16/chevron--up.svg
packages/icons/src/svg/16/close.svg
packages/icons/src/svg/16/overflow-menu--horizontal.svg
packages/icons/src/svg/16/overflow-menu--vertical.svg

added 16x16 versions of caret*, chevron*, close, overflow*
Closes #
**New**
**Changed**
**Removed**

16x16 caret*, chevron*, close, overflow*

---

packages/icons/src/svg/caret--down.svg
packages/icons/src/svg/caret--left.svg
packages/icons/src/svg/caret--right.svg
packages/icons/src/svg/caret--up.svg
packages/icons/src/svg/chevron--up.svg

Remove tranparent rect layer from `caret--*`

Remove Tranparent Rects

---

README.md

Closes #101 
Add initial contributors list to the project README.md
**New**
**Changed**
- `README.md` updated with list of initial designers working on elements
**Removed**

docs(readme): add initial contributors list

---

packages/type/examples/basic/index.html
packages/type/examples/basic/styles.scss
packages/type/scss/_classes.scss
packages/type/scss/_prefix.scss

Add type classes for website and digital.
**New**
- `@carbon/type`
- Now has a `_classes.scss` entrypoint that folks can opt-in to
**Changed**
- `@carbon/type` examples
- Refactored to use new type classes
**Removed**

feat(type): add type classes

---

.prettierignore
docs/developing.md
docs/icons.md
docs/publishing.md
packages/icons-angular/README.md

Closes #
**New**
**Changed**
**Removed**

docs(publishing): add docs on publishing steps

---

packages/icons-angular/README.md
packages/icons-react/README.md
packages/icons-vue/README.md
tasks/remark/remark-monorepo.js
tasks/sync.js

Update remark transform to properly create example sections.
**New**
**Changed**
- update remark transform to not create empty example sections
**Removed**

chore(package): update remark transform to not create empty example sections

---

packages/icons/src/svg/32/text--color.svg
packages/icons/src/svg/32/text-color.svg

Closes #
**New**
**Changed**
**Removed**

Rename text-color.svg to text--color.svg

---

packages/icons/src/svg/32/text--italic.svg
packages/icons/src/svg/32/text-italic.svg

Closes #
**New**
**Changed**
**Removed**

Rename text-italic.svg to text--italic.svg

---

package.json
tasks/ci-check.js

Closes #
**New**
**Changed**
**Removed**

chore(package): add icons to ignore patterns and update ci-check

---

packages/type/scss/_styles.scss

Closes #
**New**
**Changed**
**Removed**

fix(type): update styles for heading changes

---

packages/elements/package.json
packages/elements/scss/bundle.scss
packages/elements/scss/elements.scss
packages/elements/src/index.js
packages/elements/tasks/build.js

Add themes package to elements.
**New**
**Changed**
**Removed**

feat(elements): add themes to elements

---

packages/themes/src/index.js

Closes #251 
add g90 to the top level exports

Add g90 to un-nested named exports

---

packages/colors/tasks/build.js

Closes #253
Add back in ibm-color-map generation
**New**
**Changed**
- `$ibm-color-map` support in colors
**Removed**

fix(colors): add back in ibm-color-map

---

packages/colors/__tests__/scss-test.js
packages/colors/tasks/build.js

Closes #264 
**New**
- `scss` compilation test in `@carbon/colors`
**Changed**
- `@carbon/colors`
- Build step now produces accurate sass maps
**Removed**

refactor(colors): update build step and add scss test

---

.github/CONTRIBUTING.md

**Changed**
- add additional step to "Setup" to include asking dev to switch to project's preferred Node version using `.nvmrc` if possible

docs: update contributing guidelines with nvmrc info

---

packages/icons/src/svg/32/shopping--catalog.svg

Closes #
**New**
**Changed**
**Removed**

icon update

---

packages/colors/README.md

Small updates to the README to include updates to colors usage.
**Changed**
- Updates colors usage
**Removed**
- Tokens usage

docs(colors): update README to reflect updates to api

---

packages/type/scss/font-face/_mono.scss
packages/type/scss/font-face/_sans.scss
packages/type/scss/font-face/_serif.scss

Closes IBM-Design/design-website/issues/182
Update font-face files to include italics at all weights.
**New**
**Changed**
- `@carbon/type`
- Font face files updated
**Removed**

feat(type): update font-face files from google fonts

---

packages/grid/scss/12.scss
packages/grid/scss/_col.scss
packages/grid/scss/_container.scss
packages/grid/scss/_prefix.scss
packages/grid/scss/_row.scss
packages/grid/scss/aspect-ratio.scss
packages/grid/scss/grid.scss
packages/import-once/scss/import-once.scss
packages/layout/scss/_breakpoint.scss
packages/layout/scss/_convert.scss
packages/layout/scss/_key-height.scss
packages/layout/scss/_mini-unit.scss
packages/layout/scss/_spacing.scss
packages/layout/scss/_utilities.scss
packages/layout/scss/layout.scss
packages/motion/scss/motion.scss
packages/themes/examples/preview/styles.scss
packages/type/scss/_classes.scss
packages/type/scss/_font-family.scss
packages/type/scss/_prefix.scss
packages/type/scss/_reset.scss
packages/type/scss/_scale.scss
packages/type/scss/_spacing.scss
packages/type/scss/_styles.scss
packages/type/scss/bundle.scss
packages/type/scss/font-face/_mono.scss
packages/type/scss/font-face/_sans.scss
packages/type/scss/font-face/_serif.scss
packages/type/scss/type.scss

Closes #297 
**Changed**
- update sass copyright banners

chore: update sass copyright banners

---

packages/grid/scss/_col.scss

Closes #295
**New**
**Changed**
- add offset-0 class names
**Removed**

feat(grid): add offset-0 class names

---

packages/grid/package.json
packages/grid/scss/12.scss
packages/grid/scss/_col.scss
packages/grid/scss/_container.scss
packages/grid/scss/_row.scss
packages/grid/scss/grid.scss
packages/import-once/scss/import-once.scss
packages/layout/scss/_breakpoint.scss
packages/layout/scss/_convert.scss
packages/layout/scss/_key-height.scss
packages/layout/scss/_mini-unit.scss
packages/layout/scss/_spacing.scss
packages/layout/scss/_utilities.scss
packages/motion/README.md
packages/motion/scss/motion.scss
packages/type/scss/_classes.scss
packages/type/scss/_font-family.scss
packages/type/scss/_reset.scss
packages/type/scss/_scale.scss
packages/type/scss/_spacing.scss
packages/type/scss/_styles.scss
packages/type/scss/bundle.scss

Add `carbon--` namespace to public Sass API. Changes were made running https://github.com/carbon-design-system/carbon-upgrade on the project.
For a preview of this tool, check out: https://mobile.twitter.com/__joshblack/status/1089326485196992512
**New**
**Changed**
- All files with a public API now have a `carbon--` prefix on: variables, mixins, and functions
**Removed**
Looking for feedback around:
- Will this strategy work for reducing the number of collisions?
- After seeing the implementation, do we believe that this will scale out across core projects?
- Any other lingering concerns that should be called out now?

[RFC] feat/add-namespace

---

.circleci/config.yml

Closes #
**New**
**Changed**
**Removed**

chore(project): switch to workflow for checks

---

packages/app-icons/app-icon-template/README.md

Update README.md for app-icon-template

---

packages/app-icons/README.md

update readme for app-icons

---

packages/themes/src/g10.js
packages/themes/src/white.js

Closes carbon-design-system/carbon-website#1048
Changing Green60 to Green50 on light themes.

green60 to green50

---

packages/app-icons/app-icon-template/App_Icon_Template.ai

Need to update app icon template file. Uploading a new file

Delete App Icon Template

---

packages/type/scss/_styles.scss
packages/type/src/__tests__/__snapshots__/styles-test.js.snap
packages/type/src/__tests__/exports-test.js
packages/type/src/styles.js

There's been an ask from the Watson team and Wonil for this addition; it's the same as $expressive-heading-05 but semibold.

update(type):add $expressive-heading-06

---

packages/icons/src/svg/16/redo.svg
packages/icons/src/svg/16/undo.svg
packages/icons/src/svg/20/redo.svg
packages/icons/src/svg/20/undo.svg
packages/icons/src/svg/24/redo.svg
packages/icons/src/svg/24/undo.svg
packages/icons/src/svg/32/redo.svg
packages/icons/src/svg/32/undo.svg

added icon assets for undo/redo
Closes #362 #363 
Added SVG assets for undo/redo, and all 4 sizes. Thanks @m-battelli for the submission!
**New**
16/redo.svg
16/undo.svg
20/redo.svg
20/undo.svg
24/redo.svg
24/undo.svg
32/redo.svg
32/undo.svg

undo & redo icons

---

docs/migration/10.x-color.md
docs/migration/10.x-icons.md
docs/migration/10.x-type.md

Closes #
**New**
**Changed**
**Removed**

docs: add initial migration docs

---

packages/elements/scss/elements.scss
packages/elements/scss/index.scss
packages/grid/scss/_col.scss
packages/grid/scss/_container.scss
packages/grid/scss/_row.scss

Closes #356
Update comment syntax
**New**
**Changed**
- Update comment syntax to `//` or `///`
**Removed**

chore: change comment syntax

---

docs/migration/10.x-motion.md

Closes #398
Add motion migration guide.
**New**
- Add motion migration guide
**Changed**
**Removed**

docs(migrate): add migration docs for motion

---

packages/layout/scss/_breakpoint.scss

Fixes #431.
**New**
- Support for custom breakpoints for the following:
- `carbon--breakpoint-up()`
- `carbon--breakpoint-down()`
- `carbon--breakpoint-between()`
- `carbon--breakpoint()`
**Changed**
- Some SassDoc comment change to sync with the code.

feat(layout): support number in breakpoint API

---

.circleci/config.yml

Closes #
**New**
**Changed**
**Removed**

chore(ci): update yarn to v1.15.2

---

packages/colors/package.json
packages/test-utils/package.json
packages/themes/package.json

Closes #
**New**
**Changed**
**Removed**

feat(test-utils): make test-utils public

---

packages/icons/README.md
packages/icons/examples/preview/index.html
packages/icons/examples/preview/index.js
packages/icons/examples/preview/package.json
packages/icons/examples/preview/styles.scss
packages/icons/examples/preview/yarn.lock

Closes #
**New**
**Changed**
**Removed**

docs(icons): update icon docs

---

packages/layout/examples/preview/index.html
packages/layout/examples/preview/styles.scss
packages/layout/scss/_spacing.scss

Closes #
**New**
**Changed**
**Removed**

feat(layout): update spacing scale

---

README.md

v10 Release

---

packages/elements/package.json
packages/elements/scss/elements.scss
packages/elements/scss/index.scss

Add `@carbon/icons` scss support for elements
**New**
**Changed**
- Add `@carbon/icons` scss support for elements
**Removed**

feat(elements): add icons scss support

---

packages/type/examples/preview/index.js

Closes #473 
**Changed**
- update Step in preview documentation so that it doesn't start at 0

fix(type): update step in preview documentation

---

packages/icons/README.md

Closes #504
**New**
**Changed**
- Update icons README to include docs on styling inner path
**Removed**

docs(icons): add docs for styling inner path

---

docs/icons.md

Closes https://github.com/IBM/carbon-elements/issues/489#issuecomment-487393448
**New**
Add a section called "updating metadata" with steps needed to create a PR to update an icon's aliases entrie in `metadata.yml`
**Note** 
Hey @joshblack I'm not the best content person so feel free to make edits / structural changes to the section. Let me know if this covers the need. Thank you!

Update icons.md to include "updating metadata"
